# -*- coding: utf-8 -*-
"""PythonBasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBMSWtnTOw8Jnw2IF1dBSbxEtYrqsTVN

#Basics Function
"""

print("Machine Learning")

print('Machine Learning')

print("Machine Learning" +" Project")

print(6)

print(8+8)

"""#Basic Data Types:
1.  Integer
2.  Float
33. String

"""

type(2)

type(4.43)

type("Kunal Sharma")

"""#Constant & Variable"""

superhero = "Iron Man"
print(superhero)

super_hero = "Iron Man"
print(super_hero)

super_hero = "Iron Man"
print("super_hero")

Hero1, Hero2, Hero3 = "BatMan" , "Captain America" , "Iron Man"
print(Hero1)
print(Hero2)
print(Hero3)

x=y=z=54
print(x)
print(y)
print(z)

"""# Input  Function

"""

num1 = int(input("Enter the first number : "))
num2 = int(input("Enter the second number : "))
sum = num1 + num2
print(sum)

num1 = input("Enter the first number : ")
num2 = input("Enter the second number : ")
sum = num1 + num2
print(sum)

#change the data types in  python
num = 5
print(float(num))

"""#Basics Data Types in Python
1. Integer
2. Floating Point
3. Complex
4. Boolean
5. String
"""

# Integer
a = 1
print(a)

type(a)

#Floaating Point
b=2.3
print(b)
type(b)

#Complex Number
c = 1 + 2j
print(c)
type(c)

"""Conversion of one data type to another

"""

# int to float
x = 10
print(x)
type(x)

y = float(x)
print(y)
type(y)

#float to int
y = 10.2
print(y)
type(y)

x = int(y)
print(x)
type(x)

"""Boolean
1. True
2. False
"""

a = True
print(a)
type(a)

b = False
print(b)
type(b)

a = 7<4
print(a)
type(a)

b = 13>11
print(b)
type(b)

"""String"""

print("Machine Learning")

print('Machine Learing')

my_string = "Machin Learning"
print(my_string)
type(my_string)

print("Hello" * 5)

"""Slicing

"""

my_string = "Programming"
print(my_string[1:9]) #value for 1 to 5-1 will be sliced

print(my_string[0:10:2])

"""String Concatenation"""

word_1 = "Machine "
word_2 = "Learning"
print(word_1 + word_2)